import type { GlobalThemeOverrides, MessageProviderProps } from 'naive-ui';
import { colors } from '~/tailwind.config';

type MessageThemeOverrides = NonNullable<MessageProviderProps['themeOverrides']>;
export const messageOverrides: MessageThemeOverrides = {
  iconColor: colors.primary.DEFAULT,
  iconColorError: colors.statusRed,
  iconColorWarning: colors.statusYellow,
  iconColorSuccess: colors.statusGreen,
  iconColorInfo: colors.statusBlue.DEFAULT,
  color: colors.grey.lighter,
  colorError: colors.grey.lighter,
  colorWarning: colors.grey.lighter,
  colorSuccess: colors.grey.lighter,
  colorInfo: colors.grey.lighter,
};

/**
 * Theme configs
 */
export const themeOverrides: GlobalThemeOverrides = {
  common: {
    bodyColor: colors.grey.DEFAULT,
    primaryColor: colors.primary.DEFAULT,
    primaryColorHover: colors.primary.light,
    primaryColorPressed: colors.primary.light,
    borderColor: colors.bg.DEFAULT,
    borderRadius: '8px',
    textColorBase: colors.white,
  },
  DataTable: {
    tdColor: colors.grey.dark,
    thColor: colors.grey.dark,
    borderColor: colors.transparent,
    borderRadius: '8px',
    tdColorHover: colors.grey.light,
  },
  DatePicker: {
    iconColor: colors.grey.dark,
    color: colors.grey.dark, // background of the picker
    panelColor: colors.grey.dark, // panel background
    itemTextColor: colors.white,
    itemTextColorActive: colors.white,
    itemTextColorDisabled: colors.grey.lighter,
    itemColorActive: colors.primary.DEFAULT,
    itemColorInRange: colors.primary.light,
    itemColorHover: colors.primary.light,
    itemColorDisabled: colors.grey.light,
    itemBorderRadius: '8px',
    calendarDaysColor: colors.grey.dark,
    calendarTitleColor: colors.white,
    panelActionDividerColor: colors.grey.light,
    panelHeaderDividerColor: colors.grey.light,
    panelExtraFooterDividerColor: colors.grey.light,
    cellColorHover: colors.primary.light,
    cellColor: colors.grey.dark,
    cellColorInRange: colors.primary.light,
    cellColorHoverInRange: colors.primary.light,
    cellColorDisabled: colors.grey.light,
    cellTextColor: colors.white,
    cellTextColorDisabled: colors.grey.lighter,
    cellTextColorActive: colors.white,
    cellTextColorInRange: colors.white,
    cellTextColorHover: colors.white,
    peers: {
      Button: {
        colorPrimary: colors.grey.light,
        colorFocusPrimary: colors.grey.lighter,
        colorHoverPrimary: colors.grey.lighter,
        colorPressedPrimary: colors.grey.lightest,
        textColorPrimary: colors.white,
        textColorHoverPrimary: colors.white,
      },
    },
  },
  Dropdown: {
    color: colors.bg.DEFAULT,
    colorActive: colors.bg.DEFAULT,
    colorActiveError: colors.bg.DEFAULT,
    colorActiveWarning: colors.bg.DEFAULT,
    colorDisabled: colors.primary.dark,
  },
  AutoComplete: {
    peers: { InternalSelectMenu: { color: colors.grey.light } },
  },
  Input: {
    border: `1px solid ${colors.grey.light}`,
    borderDisabled: `1px solid ${colors.primary.dark}`,
    borderFocus: `1px solid ${colors.primary.DEFAULT}`,
    borderError: `1px solid ${colors.yellow}`,
    borderFocusError: `1px solid ${colors.grey.DEFAULT}`,
    borderFocusWarning: `1px solid ${colors.bg.DEFAULT}`,
    borderHover: `1px solid ${colors.grey.light}`,
    borderHoverError: `1px solid ${colors.grey.DEFAULT}`,
    borderHoverWarning: `1px solid ${colors.grey.light}`,
    borderWarning: `1px solid ${colors.grey.light}`,
    caretColor: colors.white,
    clearColor: colors.grey.DEFAULT,
    clearColorHover: colors.white,
    clearColorPressed: colors.white,
    color: colors.grey.dark,
    colorFocus: colors.grey.dark,
    colorFocusError: colors.grey.dark,
    colorFocusWarning: colors.grey.dark,
    colorDisabled: colors.grey.dark,
    heightTiny: '30px',
    heightSmall: '34px',
    heightMedium: '40px',
    heightLarge: '48px',
    iconColor: colors.black,
    iconColorHover: colors.black,
    loadingColor: colors.white,
    placeholderColor: colors.grey.lightest,
    suffixTextColor: colors.white,
    textColor: colors.white,
    textColorDisabled: colors.grey.lighter,
  },
  InputNumber: {
    common: {},
  },
  Layout: {
    textColor: colors.white,
    color: colors.bg.box,
    siderColor: colors.bg.box,
  },
  Menu: {
    arrowColorActiveInverted: colors.primary.dark,
    arrowColorChildActiveInverted: colors.primary.dark,
    arrowColorChildActiveHoverInverted: colors.primary.dark,
    arrowColorChildInverted: colors.primary.dark,
    arrowColorChildHoverInverted: colors.primary.dark,
    arrowColorInverted: colors.primary.dark,
    arrowColorHoverInverted: colors.primary.dark,
    fontSize: '14px',
    groupTextColorInverted: colors.white,
    itemColorActiveInverted: colors.bg.light,
    itemColorActiveHoverInverted: colors.bg.light,
    itemTextColorInverted: colors.white,
    itemTextColorActiveInverted: colors.white,
    itemTextColorActiveHoverInverted: colors.white,
    itemTextColorHoverInverted: colors.white,
  },
  Pagination: {
    buttonColor: colors.grey.light,
    buttonColorHover: colors.grey.lighter,
    buttonColorPressed: colors.grey.lighter,
    buttonIconColor: colors.primary.DEFAULT,
    buttonIconColorHover: colors.primary.DEFAULT,
    buttonIconColorPressed: colors.primary.DEFAULT,
    itemTextColor: colors.white,
    itemTextColorActive: colors.white,
    itemTextColorHover: colors.white,
    itemTextColorPressed: colors.white,
    itemTextColorDisabled: colors.primary.dark,
  },
  Radio: {
    buttonHeightSmall: '26px',
    buttonHeightMedium: '34px',
    buttonHeightLarge: '38px',
    buttonBorderRadius: '15px',
    buttonBoxShadow: '0px 0px 0px 0px transparent',
    buttonBoxShadowFocus: '0px 0px 0px 0px transparent',
    buttonBoxShadowHover: '0px 0px 0px 0px transparent',
    buttonColor: colors.grey.DEFAULT,
    buttonColorActive: colors.green.DEFAULT,
    buttonBorderColor: colors.transparent,
    buttonBorderColorActive: colors.transparent,
    buttonBorderColorHover: colors.transparent,
    buttonTextColor: colors.black,
    buttonTextColorActive: colors.black,
    buttonTextColorHover: colors.black,
  },
  Select: {
    peers: {
      InternalSelection: {
        arrowColor: colors.white,
        border: `1px solid ${colors.bg.DEFAULT}`,
        borderFocus: `1px solid ${colors.grey.light}`,
        borderError: `1px solid ${colors.yellow}`,
        borderFocusError: `1px solid ${colors.grey.DEFAULT}`,
        borderFocusWarning: `1px solid ${colors.bg.DEFAULT}`,
        borderHover: `1px solid ${colors.grey.light}`,
        borderHoverError: `1px solid ${colors.grey.DEFAULT}`,
        borderHoverWarning: `1px solid ${colors.grey.light}`,
        borderWarning: `1px solid ${colors.grey.light}`,
        caretColor: colors.grey.DEFAULT,
        caretColorError: colors.grey.DEFAULT,
        caretColorWarning: colors.grey.DEFAULT,
        clearColor: colors.grey.DEFAULT,
        clearColorHover: colors.grey.DEFAULT,
        clearColorPressed: colors.grey.DEFAULT,
        color: colors.grey.light,
        colorActive: colors.bg.DEFAULT,
        colorActiveError: colors.bg.DEFAULT,
        colorActiveWarning: colors.bg.DEFAULT,
        colorDisabled: colors.primary.dark,
        fontSizeMedium: '14px',
        fontWeight: 'medium',
        heightTiny: '28px',
        heightSmall: '34px',
        heightMedium: '38px',
        heightLarge: '48px',
        loadingColor: colors.grey.DEFAULT,
        placeholderColor: colors.grey.lightest,
        paddingSingle: '0 20px',
        textColor: colors.white,
        textColorDisabled: colors.grey.lighter,
      },
      InternalSelectMenu: {
        color: colors.grey.light,
        optionColorActive: colors.bg.DEFAULT,
        optionColorActivePending: colors.bg.DEFAULT,
        optionColorPending: colors.grey.lighter,
        optionCheckColor: colors.bg.DEFAULT,
        optionTextColor: colors.white,
        optionTextColorPressed: colors.white,
        optionTextColorDisabled: colors.grey.lighter,
        optionTextColorActive: colors.white,
        paddingTiny: '0px',
        paddingSmall: '3px',
        paddingMedium: '5px',
        paddingLarge: '7px',
        paddingHuge: '10px',
      },
    },
  },
  Slider: {
    dotColor: colors.primary.light,
    fillColor: colors.primary.DEFAULT,
    fillColorHover: colors.primary.DEFAULT,
    handleColor: colors.primary.light,
    indicatorColor: colors.grey.light,
    indicatorTextColor: colors.white,
    railColor: colors.body.light,
    railColorHover: colors.body.light,
  },
  Switch: {
    railColor: colors.grey.light,
  },
};
